version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: eecs4413-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eecs4413-network

volumes:
  mysql_data:

networks:
  eecs4413-network:
    driver: bridge
